"""4 Migration

Revision ID: 8dbcd4e548c5
Revises: 0ede6955afb0
Create Date: 2019-07-10 15:27:55.087809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dbcd4e548c5'
down_revision = '0ede6955afb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('roomName', sa.String(length=255), nullable=False),
    sa.Column('telephone', sa.Boolean(), nullable=False),
    sa.Column('projector', sa.Boolean(), nullable=False),
    sa.Column('whiteboard', sa.Boolean(), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.add_column('booking', sa.Column('cost', sa.Integer(), nullable=False))
    op.add_column('booking', sa.Column('roomId', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'booking', ['id'])
    op.create_foreign_key(None, 'booking', 'room', ['roomId'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'booking', type_='foreignkey')
    op.drop_constraint(None, 'booking', type_='unique')
    op.drop_column('booking', 'roomId')
    op.drop_column('booking', 'cost')
    op.drop_table('room')
    # ### end Alembic commands ###
